### ISSUE TITLE
needs rethinking

### ISSUE THREAD

**Issue by tolgraven** [fisherman/grc#1]
Appears to me that by wrapping even the "unwrapped" commands (but then just passing them through) the user loses the ability to actually modify those commands, which is presumably the entire reason for not wrapping them in the first place.
Eg my cat:
`type -q ccat; 
and command ccat $argv;  
or command cat $argv`

Fixed by putting my cat.fish and ls.fish in conf.d, giving them precedence, but feels like it would be cleaner if fisherman/grc behaved more reasonably in the first place :)

**Comment by brj** [comment]
You can customize what commands are wrapped with `set grc_wrap_commands ...`. Commands that do not appear in that list will not be wrapped at all.

<img width="785" alt="screen shot 2016-05-30 at 9 56 10 pm 1" src="https://cloud.githubusercontent.com/assets/8317250/15650144/7856ad14-26b1-11e6-8b1a-3bfe11b81af2.png">

**Comment by tolgraven** [comment]
That's what I mean. You take control over even the commands that have been dropped, leaving the user's original/own wrapping (backed up as copy-cat.fish etc) unused. So the choice ends up either grc or nothing.
![screen shot 2016-05-30 at 15 36 26](https://cloud.githubusercontent.com/assets/9143357/15650968/b193bca0-267c-11e6-85fa-33ee7a1a423f.png)

**Comment by tolgraven** [comment]
hmm btw should I try to clean up the code for my prompt_pwd <> finder label func and put it up? Been thinking about it but then something tells me I'm probably the only person around who actually uses labels, hehe.

**Comment by brj** [comment]
Labels?

With regards to the issue, I see what you mean now. I'll try to think of something that does not compromise the reason why I put each command in a function. 

I was using [omf/plugin-grc](https://github.com/oh-my-fish/plugin-grc), but it was slowing down my shell noticeably, so I wrote fisherman/grc.

**Comment by brj** [comment]
BTW I recommend you create a `tolgraven` plugin that has all your functions, completions, etc. and install that as a local plugin with fisherman to simplify things, but you can keep using your ~/.config/fish/functions directory to store and manage your own created functions yourself. 

Either way, the way to solve this issue is using a custom `fish_path`. 

If you set a variable:

```
set -U fish_path ~/my/prefix
```

fisherman will install plugins into `~/my/prefix/{functions,completions,conf.d}` instead of `~/.config/fish/{functions,completions,conf.d}.

**Comment by brj** [comment]
@tolgraven 

You can get what you want using a [custom fish_path](https://github.com/fisherman/fisherman#where-does-fisherman-put-stuff). 

```fish
set -U fish_path ~/my/prefix
```

This will cause fisherman to install plugins into:

*  **~/my/prefix/{functions,completions,conf.d}**
* *instead of* ~/.config/fish/{functions,completions,conf.d} (default behavior)

This way, fisherman/grc, as well as other plugins installed using fisherman can't possibly interfere with custom created functions or snippets. 

Make sure to add the fish_path to your `fish_function_path` and `fish_complete_path`, as fisherman is **not** responsible for that.

```fish
# config.fish
set fish_function_path ~/my/prefix/functions $fish_function_path
set fish_complete_path ~/my/prefix/completions $fish_complete_path

# and for snippet support
for file in ~/my/prefix/conf.d/*.fish
    source $file
end
```

I prefer the default behavior to avoid setting a fish_path, but this option exists for users like you.



<h1></h1>
**Sidenote**:
BTW I recommend you create a `tolgraven` plugin that has all your functions, completions, etc. and install that as a local plugin with fisherman to simplify things, but you can keep using your ~/.config/fish/functions directory to store and manage your own created functions yourself.

**Comment by tolgraven** [comment]
Yeah I need  to clean it up in general, got about 200 functions... But always felt like a good separation with omf/earlier fisherman when the func dir had only my stuff, plugins were loaded from elsewhere instead of symlinked in, only upgraded from 1.5 just now because 2.0 broke everything something fierce. So the path thing sounds perfect!

And yeah, "Labels?", that's what I mean haha. Well apparently they're called tags now. Just something I thought of after making the screen cap, not related to this obvs.
![screen shot 2016-05-30 at 16 10 04](https://cloud.githubusercontent.com/assets/9143357/15651895/b82f82d2-2682-11e6-9ea8-f29ae9c5c8bd.png)

**Comment by brj** [comment]
> Well apparently they're called tags now. Just something I thought of after making the screen cap, not related to this obvs.

Ah, sure. That's a nifty feature and I am sure other people use it too. You are not alone :)

> But always felt like a good separation with omf/earlier fisherman when the func dir had only my stuff...

You can achieve a directory setup similar to `~1.5` using $fish_path.

If you try it out, please let me know how it goes, and if everything works as expected :)

**Comment by tolgraven** [comment]
Alright I'll give it a go, cheers.

Plan was to generalize it so it can be used for not just prompts but whatever. And also incorporate your imgcat with osxutils geticon and get ll with both icons and colors from Finder. Would be bare sweet (and probably slow as shit haha). Also something tells me I'll never get around to it ;(

**Comment by brj** [comment]
It won't slow you down a bit. As long as you are not definiting abbreviation or aliases in your config.fish, this will not slow you down more than `0.01ms`.

**Comment by brj** [comment]
Closing as tentatively resolved, now that a solution was given.

**Comment by tolgraven** [comment]
Oh no I was talking about the other thing
Extracting/resizing/imgcating every files' icon on the fly for ls/ll/la I
can't see not being slow ;)

**Comment by brj** [comment]
Ah, :0 
Good luck with that.

**Comment by tolgraven** [comment]
Yup, works fine! Cheers man.  Although with original instructions it just got borked worse (obviously, in retrospect), but easy enough to sort:

```
set -q fish_path; or set -U fish_path ~/.config/fish/fisherman

if not contains $fish_function_path $fish_path/functions
    set fish_function_path[1] $fish_path/functions
    set fish_function_path ~/.config/fish/functions $fish_function_path
end
if not contains $fish_complete_path $fish_path/completions
    set fish_complete_path[1] $fish_path/completions
    set fish_complete_path ~/.config/fish/completions $fish_complete_path
end
for file in $fish_path/conf.d/*.fish
    source $file
end
```

Wouldn't this make more sense as default behavior, anyways? Apart from (imo) it being nice having stuff separated it also makes sure fisherman has minimal impact and doesn't railroad any of the user's setup regardless of any plugin quirks - your own stuff always has last say.
